apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-connect-obs
  namespace: dynatrace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-connect-obs
rules:
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list","patch","update","create"]
  - apiGroups:
      - "core.openfeature.dev"
    resources:
      - featureflags
      - featureflagsources
      - flagds
    verbs:
      - get
      - list
      - watch
      - create
      - patch
  - apiGroups:
    - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - nodes/stats
      - nodes/proxy
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-connect-obs
roleRef:
  kind: ClusterRole
  name: edge-connect-hpa
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: edge-connect-obs
    namespace: dynatrace
---
apiVersion: dynatrace.com/v1alpha2
kind: EdgeConnect
metadata:
  name: obs-istio-edgeconnect
  namespace: dynatrace
spec:
  apiServer: API_URL_TO_REPLACE
  serviceAccountName: edge-connect-obs
  replicas: 1
  oauth:
    provisioner: true
    clientSecret: edgeconnect-oauth
    endpoint: https://SSO_URL_TO_REPLACE
    resource: "URN_TO_REPLACE"
  kubernetesAutomation:
    enabled: true